// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtI0qNnirbNCnEhXabzz3KkfEBmvIXWuQ',
    appId: '1:59023748498:web:4ab08b3a2b37f27e80a54b',
    messagingSenderId: '59023748498',
    projectId: 'kopma-uin-suka-8a085',
    authDomain: 'kopma-uin-suka-8a085.firebaseapp.com',
    storageBucket: 'kopma-uin-suka-8a085.appspot.com',
    measurementId: 'G-J7GD364FF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJQxGKj9GRVDlFwoEwk0_EykTKS5F8Dcs',
    appId: '1:59023748498:android:963159b04d513ae680a54b',
    messagingSenderId: '59023748498',
    projectId: 'kopma-uin-suka-8a085',
    storageBucket: 'kopma-uin-suka-8a085.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoA8uemrIb84jBymwgNIZWZSEuWf5lG4s',
    appId: '1:59023748498:ios:345324a8b23072b380a54b',
    messagingSenderId: '59023748498',
    projectId: 'kopma-uin-suka-8a085',
    storageBucket: 'kopma-uin-suka-8a085.appspot.com',
    iosBundleId: 'com.example.kopma',
  );
}
const iOSClientId = '59023748498-dq7er6g5petf41p7a9neb9a9m8ddgj25.apps.googleusercontent.com';
const webClientId = '59023748498-gb7ne9699v10r8hr8a0mdgv2m8ciq6b6.apps.googleusercontent.com';


String get googleClientId {
  return switch (defaultTargetPlatform) {
    TargetPlatform.iOS || TargetPlatform.macOS => iOSClientId,
    _ => webClientId,
  };
}
